project:
  type: website

website:
  title: "Data Science Initiative"
  navbar:
    logo: DSI_Pics/DSI_Avatar_03.ico

    left:
      - news.qmd
      - text: Mission
        href: https://www.csuchico.edu/datascience/mission.shtml
      - projects.qmd
      - text: NorCal DataFest!
        href: https://norcaldatafest.netlify.app/
    right: 
      - icon: github
        menu: 
          - text: CSUC DSI
            url: https://github.com/csucdsi
          - text: Math 490
            url: https://github.com/DATA-490        

format:
  html:
    highlight-style: a11y
    theme:
      light: Chico_Light.scss
      dark: Chico_Dark.scss
    highlight: pygments
    toc: true
    code-copy: true
    code-overflow: scroll
    callout-icon: false

editor: visual

execute: 
  freeze: auto
  echo: false
  warning: false
  