project:
  type: website

website:
  title: "Data Science Initiative"
  navbar:
    right:
      - news.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    highlight-style: a11y
    theme:
      light: Chico_Light.scss
      dark: Chico_Dark.scss
    highlight: pygments
    toc: true
    code-copy: true
    code-overflow: scroll
    callout-icon: false

editor: visual

execute: 
  freeze: auto
  echo: false
  warning: false
  